language: node_js
node_js:
  - 14
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - yarn install
scripts:
  - yarn docs:build
deploy:
  provider: pages
  local_dir: ./docs/.vuepress/dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target-branch: gh-pages # 构建后的静态资源提交到这个分支
  keep_history: true
  on:
    branch: master